{
  "hash": "2c4c23fe0a61bf4488082b1972d4e469",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Who Do We Know the Least About?\"\nsubtitle: \"Measuring uncertainty in American Community Survey data\"\nauthor: \"Carenna Thompson\"\ndate: 2026-09-05\nformat:\n  html:\n    toc: true\n    code-fold: false\nexecute:\n  warning: false\n  message: false\n---\n\n\n## Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidycensus)\nlibrary(knitr)\n```\n:::\n\n\n\n## The question\n\nIn this analysis, I look at median gross rent across counties in California, and\nask which communities we measure most and least reliably.** I am looking at California because I grew up in Sacramento. There are a wide range of counties and rent prices throughout the state so I thought it would be an apt state and variable to look at when measuring reliability. \n\n---\n\n## Choosing what to measure\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_state = \"CA\"\nmy_variable = \"B25064_001\"\n```\n:::\n\n\n## Pulling the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# lets find some data\nca_rent <-get_acs(\n  geography = \"county\",\n  variables = \"B25064_001\",\n  state = \"CA\",\n  year = 2023,\n  survey = \"acs5\"\n)\n```\n:::\n\n\nLet's look at what came back.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#we can view it like...\n\ndim(ca_rent)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 58  5\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(ca_rent)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  GEOID NAME                         variable   estimate   moe\n  <chr> <chr>                        <chr>         <dbl> <dbl>\n1 06001 Alameda County, California   B25064_001     2318    17\n2 06003 Alpine County, California    B25064_001       NA    NA\n3 06005 Amador County, California    B25064_001     1380   106\n4 06007 Butte County, California     B25064_001     1369    31\n5 06009 Calaveras County, California B25064_001     1615   142\n6 06011 Colusa County, California    B25064_001     1139    67\n```\n\n\n:::\n:::\n\n\n\n**There are 58 counties in California and my row count matches that.**\n\n---\n\n## How big is the margin of error?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#margin of error studies\n\nca_rent = ca_rent %>%\n  mutate(moe_pct = as.numeric(moe) / as.numeric(estimate) * 100)\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#lets take a look \n  \nca_rent %>%\n  arrange(desc(moe_pct))%>%\n  select (NAME, estimate, moe, moe_pct) %>%\n  head (10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   NAME                         estimate   moe moe_pct\n   <chr>                           <dbl> <dbl>   <dbl>\n 1 Sierra County, California        1181   705   59.7 \n 2 Trinity County, California        922   220   23.9 \n 3 Plumas County, California        1034   148   14.3 \n 4 Mono County, California          1593   212   13.3 \n 5 Mariposa County, California      1268   165   13.0 \n 6 Calaveras County, California     1615   142    8.79\n 7 Modoc County, California          818    71    8.68\n 8 Lake County, California          1292   110    8.51\n 9 Tuolumne County, California      1247   103    8.26\n10 Inyo County, California          1140    88    7.72\n```\n\n\n:::\n:::\n\n\n\nSierra County has the largest margin of error relative to its estimate at 705 MOE to an estimate of 1181. The MOE percent is around 59.7%.\n\n---\n\n## Sorting counties into reliability categories\n\n\n::: {.cell}\n\n```{.r .cell-code}\nca_rent = ca_rent %>%\n  mutate(reliability = case_when(\n    moe_pct < 5 ~ \"High confidence\",\n    moe_pct < 10 ~ \"Moderate\",\n    TRUE        ~ \"Low confidence\"\n))\ncount(ca_rent, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High confidence    39\n2 Low confidence      6\n3 Moderate           13\n```\n\n\n:::\n:::\n\n\n\n39 counties fall into the high confidence with a MOE percentage of under 5%. 13 counties fall into the moderate with a MOE percentage of under 15%. 6 counties fall into the low confidence with a MOE percentage above 15%\n\n---\n\n## Is the margin of error bigger in small places?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nca_wide = get_acs (\n  geography = \"county\",\n  variables = c(myvar = \"B25064_001\",\n                pop   = \"B01003_001\"),\n  state = \"CA\",\n  year  = 2023,\n  survey = \"acs5\",\n  output = \"wide\"\n)\nhead(ca_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                         myvarE myvarM    popE  popM\n  <chr> <chr>                         <dbl>  <dbl>   <dbl> <dbl>\n1 06001 Alameda County, California     2318     17 1651949    NA\n2 06003 Alpine County, California        NA     NA    1695   234\n3 06005 Amador County, California      1380    106   41029    NA\n4 06007 Butte County, California       1369     31  209470    NA\n5 06009 Calaveras County, California   1615    142   45995    NA\n6 06011 Colusa County, California      1139     67   21895    NA\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nca_wide = ca_wide %>%\n  mutate(moe_pct = myvarM / myvarE * 100) %>%\n  mutate(reliability = case_when (\n           moe_pct < 5 ~ \"High confidence\",\n          moe_pct < 10 ~ \"Moderate\", \n          TRUE         ~ \"Low confidence\"\n  \n))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary_reliability = ca_wide %>%\n  group_by(reliability) %>%\n  summarize(\n  n_counties = n(),\n  avg_population = mean(popE)\n)\n\nsummary_reliability %>%\n  kable(\n    col.names = c(\"Reliability\", \"Number of Counties\", \"Average Population\"),\n    digits = 1,\n    format.args = list(big.mark = \",\")\n  )\n```\n\n::: {.cell-output-display}\n\n\n|Reliability     | Number of Counties| Average Population|\n|:---------------|------------------:|------------------:|\n|High confidence |                 39|          989,117.8|\n|Low confidence  |                  6|           11,691.3|\n|Moderate        |                 13|           45,926.3|\n\n\n:::\n:::\n\n\nThe average population in 39 counties that has a high confidence reliability is 989,118. The table shows reliability decreasing in population with 16 counties having a moderate reliability and an average of 45,927 people and 6 counties having low confidence with an average population of 11,691.  \n\n---\n\n## What this means for policy\n\n\n\n\nSierra, Trinity, and Plumas County are the top three counties with the least reliable data in the ACS. All of these counties have lower populations than the rest of California and host national forests. Sierra county is an outlier from Trinity and Plumas County. While the average population between all of the low reliability is around 11,000, both Trinity and Plumas have populations of 15,000 and 19,000, whereas Sierra County has a population of around 2,700 (Figure 1). Additionally, Trinity and Plumas have MOE percentages of 23.9 and 14.3, respectively. This is vastly different from Sierra County who has a MOE percentage of 59.7 (Figure 1). Due to the ACS collecting data via sampling, it is likely that the low population causes less reliability due to the smaller sample size. Low population areas like Sierra County may get less responses to the survey as opposed to high population areas where there may be more people to survey and thus more chances at responses. \n\nA possible issue that may occur could be when the government uses this gross median rent to determine how much funding is allocated for emergency relief in a disaster. All three of these counties had wildfires in August 2026. Wildfires may cause loss of property, which can affect homeowners and renters. California's emergency relief organization (CALOES) may use the ACS gross median rent data to calculate the amount to give those who are in search of temporary housing or renters who may be receiving rent debt grants. If the ACS data for the gross median rent in these counties are  unreliable this could lead to an underestimate of relief grants leaving those affected by wildfires to take on more financial burdens after a national disaster.\n\n### Figure 1\n\n::: {.cell}\n\n```{.r .cell-code}\nleast_reliable = ca_wide %>%\n  arrange(desc(moe_pct)) %>%\n  slice_head(n = 3) %>%\n  select(NAME, popE, myvarE, moe_pct, reliability)\n  \nleast_reliable %>%\n  kable(\n    col.names = c(\"County\", \"Population\", \"Rent Estimate ($)\", \"MOE (%)\", \"Reliability\"),\n    digits = 1,\n    format.args = list(big.mark = \",\")\n  )\n```\n\n::: {.cell-output-display}\n\n\n|County                     | Population| Rent Estimate ($)| MOE (%)|Reliability    |\n|:--------------------------|----------:|-----------------:|-------:|:--------------|\n|Sierra County, California  |      2,731|             1,181|    59.7|Low confidence |\n|Trinity County, California |     15,886|               922|    23.9|Low confidence |\n|Plumas County, California  |     19,607|             1,034|    14.3|Low confidence |\n\n\n:::\n:::\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}